In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Iris.csv')

In [3]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
dataset.head(6)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa

In [5]:
dataset.shape

(150, 5)

In [11]:
x = dataset.iloc[:,:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = dataset["species"].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [12]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.73566663, -0.78142107,  0.13589898,  0.31686294],
       [-0.85930809,  1.50010031, -1.24710128, -1.00799954],
       [-0.85930809,  1.72825245, -1.24710128, -1.14048579],
       [ 1.11895513, -0.09696466,  0.7697741 ,  0.71432169],
       [ 0.62438933, -1.23772535,  0.71214909,  0.44934919],
       [-1.60115679, -1.69402963, -1.3623513 , -1.14048579],
       [ 1.36623803,  0.13118748,  0.71214909,  0.44934919],
       [-0.11745938, -0.3251168 ,  0.30877402,  0.1843767 ],
       [-0.85930809,  1.04379603, -1.30472629, -1.27297204],
       [ 0.62438933, -0.3251168 ,  1.11552417,  0.84680794],
       [ 1.24259658, -0.55326893,  0.65452408,  0.31686294],
       [ 0.12982352,  0.35933962,  0.65452408,  0.84680794],
       [ 0.25346497, -1.92218176,  0.19352399, -0.21308205],
       [-0.11745938, -1.23772535,  0.7697741 ,  1.11178043],
       [ 1.11895513,  0.13118748,  0.42402404,  0.31686294],
       [-0.85930809,  1.04379603, -1.30472629, -1.14048579],
       [ 0.12982352, -0.

In [14]:
X_test

array([[-1.10659099, -0.09696466, -1.30472629, -1.27297204],
       [ 1.73716239,  1.27194817,  1.40364922,  1.77421168],
       [ 0.25346497,  0.81564389,  0.48164905,  0.58183544],
       [ 0.74803078, -0.55326893,  1.11552417,  1.24426668],
       [ 1.73716239, -0.09696466,  1.23077419,  0.58183544],
       [ 0.62438933,  0.58749176,  1.34602421,  1.77421168],
       [-0.36474228, -1.00957321,  0.42402404,  0.05189045],
       [ 0.74803078,  0.35933962,  0.48164905,  0.44934919],
       [-1.10659099, -1.46587749, -0.20985108, -0.21308205],
       [ 0.00618207, -0.55326893,  0.82739911,  1.64172543],
       [ 0.00618207, -0.78142107,  0.13589898,  0.05189045],
       [-1.47751534,  1.27194817, -1.53522633, -1.27297204],
       [ 2.60265255,  1.72825245,  1.57652425,  1.11178043],
       [-0.48838373,  1.95640458, -1.3623513 , -1.00799954],
       [ 0.37710643, -0.3251168 ,  0.59689907,  0.31686294],
       [-0.36474228, -1.23772535,  0.19352399,  0.1843767 ],
       [ 0.74803078, -0.

In [15]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [16]:
y_pred = classifier.predict(X_test) 
y_pred

array(['setosa', 'virginica', 'versicolor', 'virginica', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'versicolor', 'setosa',
       'virginica', 'setosa', 'virginica', 'setosa', 'versicolor'],
      dtype='<U10')

In [17]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 8,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 12]])

In [18]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9666666666666667


In [19]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       setosa           setosa
1    virginica        virginica
2   versicolor       versicolor
3    virginica        virginica
4    virginica        virginica
5    virginica        virginica
6   versicolor       versicolor
7   versicolor       versicolor
8   versicolor       versicolor
9    virginica        virginica
10  versicolor       versicolor
11      setosa           setosa
12   virginica        virginica
13      setosa           setosa
14  versicolor       versicolor
15  versicolor       versicolor
16  versicolor       versicolor
17   virginica        virginica
18   virginica        virginica
19   virginica        virginica
20      setosa           setosa
21      setosa           setosa
22   virginica        virginica
23   virginica       versicolor
24      setosa           setosa
25   virginica        virginica
26      setosa           setosa
27   virginica        virginica
28      setosa           setosa
29  versicolor       versicolor

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[ 8  0  0]
 [ 0  9  0]
 [ 0  1 12]]
Accuracy: 0.97
Error Rate: 0.03
Precision: 0.97
Recall: 0.97
